import {
  Link01Icon,
  AiBrain01Icon,
  RoboticIcon,
  RankingIcon,
  HonorIcon,
  HonourStarIcon,
  Bookmark02Icon,
  StarIcon,
  Tag01Icon,
  LighthouseIcon,
  AnvilIcon,
  FirePitIcon,
  Activity03Icon,
  BalanceScaleIcon,
  Analytics01Icon,
  CalculateIcon,
  IdCardLanyardIcon,
  CustomerService01Icon,
  FireworksIcon,
  GitMergeIcon,
  DiscoverSquareIcon,
  DashboardSpeed01Icon,
  Timer01Icon,
  CableIcon,
  GameController03Icon,
  GlobalIcon,
  Flag03Icon,
  MapingIcon,
  SaturnIcon,
  Chat01Icon,
  Image03Icon,
} from "@hugeicons/core-free-icons";
import type { BuiltInIconName } from "~~/shared/builtin-icon-names";
import { DEFAULT_ICON } from "~~/shared/builtin-icon-names";

export const BUILTIN_ICONS = {
  "link": Link01Icon,
  "ai-brain": AiBrain01Icon,
  "robot": RoboticIcon,
  "ranking": RankingIcon,
  "honor": HonorIcon,
  "star-honor": HonourStarIcon,
  "bookmark": Bookmark02Icon,
  "star": StarIcon,
  "tag": Tag01Icon,
  "lighthouse": LighthouseIcon,
  "anvil": AnvilIcon,
  "firepit": FirePitIcon,
  "activity": Activity03Icon,
  "balance": BalanceScaleIcon,
  "analytics": Analytics01Icon,
  "calculate": CalculateIcon,
  "id-card": IdCardLanyardIcon,
  "support": CustomerService01Icon,
  "fireworks": FireworksIcon,
  "git-merge": GitMergeIcon,
  "discover": DiscoverSquareIcon,
  "dashboard": DashboardSpeed01Icon,
  "timer": Timer01Icon,
  "cable": CableIcon,
  "gamepad": GameController03Icon,
  "globe": GlobalIcon,
  "flag": Flag03Icon,
  "map": MapingIcon,
  "saturn": SaturnIcon,
  "chat": Chat01Icon,
  "image": Image03Icon,
} satisfies Record<BuiltInIconName, unknown>;

export function resolveBuiltInIcon(name: string) {
  return BUILTIN_ICONS[name] ?? BUILTIN_ICONS[DEFAULT_ICON.name];
}
